# Generated by Django 4.0.2 on 2022-02-24 09:08

import coodesh_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coodesh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfnarticles',
            name='my_id',
            field=models.BigIntegerField(default=coodesh_app.models.Tmy_id.get_latest_my_id, primary_key=True, serialize=False),
        ),
    ]
